# Huge thanks to Alacritty, as their configuration served as a starting point for this one!
# See: https://github.com/alacritty/alacritty

name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      WX_WIDGETS_BUILD_OUT_DIR: "${{github.workspace}}/wx-widgets-build"

    steps:
      - uses: actions/checkout@v2
      # - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
      - name: Install rust-script and cargo-make
        run: |
          cargo install rust-script --version "0.7.0"
          cargo install cargo-make --version 0.37.5
      # wxWidgets builds (internal to espanso-modulo) are by far the largest bottleneck
      # in the current pipeline, so we cache the results for a faster compilation process
      - name: "Cache wxWidgets builds"
        if: ${{ runner.os != 'Linux' }}
        uses: actions/cache@v3
        with:
          path: |
            ${{env.WX_WIDGETS_BUILD_OUT_DIR}}
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('espanso-modulo/build.rs') }}-${{ hashFiles('espanso-modulo/vendor/*') }}
      - name: Build with cargo
        run: |
           cargo build -p espanso --no-default-features --features modulo,native-tls
      - name: Build
        run: |
          cargo make build-binary
      - name: Check clippy
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
